/* LOGIN TYPES */
export const AUTHENTICATION_SIGN_IN = "AUTHENTICATION_SIGN_IN";
export const AUTHENTICATION_SIGN_OUT = "AUTHENTICATION_SIGN_OUT";
export const AUTHENTICATION_SIGN_UP = "AUTHENTICATION_SIGN_UP";
export const AUTHENTICATION_CONFIRM_REGISTRATION = "AUTHENTICATION_CONFIRM_REGISTRATION";
export const AUTHENTICATION_RESEND_CODE = "AUTHENTICATION_RESEND_CODE";
export const AUTHENTICATION_CHANGE_PASSWORD = "AUTHENTICATION_CHANGE_PASSWORD";

/* NAVIGATION TYPES */
export const NAVIGATION_HOME = "NAVIGATION_HOME";
export const NAVIGATION_LANDING = "NAVIGATION_LANDING";
export const NAVIGATION_AUTHENTICATION_SWITCH_FORM = "NAVIGATION_AUTHENTICATION_SWITCH_FORM";
export const NAVIGATION_AUTHENTICATION_SIGN_IN = "NAVIGATION_AUTHENTICATION_SIGN_IN";
export const NAVIGATION_AUTHENTICATION_SIGN_UP = "NAVIGATION_AUTHENTICATION_SIGN_UP";
export const NAVIGATION_AUTHENTICATION_CONFIRM_REGISTRATION = "NAVIGATION_AUTHENTICATION_CONFIRM_REGISTRATION";