/* LOGIN TYPES */
export const AUTHENTICATE_SIGN_IN = "AUTHENTICATE_SIGN_IN";
export const AUTHENTICATE_SIGN_OUT = "AUTHENTICATE_SIGN_OUT";
export const AUTHENTICATE_SIGN_UP = "AUTHENTICATE_SIGN_UP";

